routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ProductController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('welcome');


Route::get('/products', [ProductController::class, 'list'])->name('productList');
Route::post('/products', [ProductController::class, 'search'])->name('productSearch');

Route::post('/products/addToChart', [ProductController::class, 'addToChart'])->name('addToChart');
Route::get('/products/emptyChart', [ProductController::class, 'emptyChart'])->name('emptyChart');
Route::get('/products/new', [ProductController::class, 'new']);
//Definimos la accion de save cuando se envia el formulario
Route::post('/products/new', [ProductController::class, 'save'])->name('saveProduct');
//Route::get('/axios', [ProductController::class, 'list']);

/**
 * LOGIN ROUTES
 */
Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');

require __DIR__ . '/auth.php';

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

app/View/Components/GuestLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class GuestLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.guest');
    }
}

resources/views/dashboard.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Dashboard') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    You're logged in!
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/new_product.blade.php
<x-guest-layout>
    <h1>Crear Productos</h1>
    <div class="card">
        <div class="card-body">
            <form id="filterForm" method="post" action={{ route('saveProduct') }} enctype="multipart/form-data">
                {{ csrf_field() }}
                <div class="form-group">
                    <label for="name">Name</label>
                    <input id="name" type="text" name="name" value="" class="form-control">
                    @error('name')
                    <div class="error">{{ $message }}</div>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="price">Precio</label>
                    <input id="price" type="number" name="price" value="" class="form-control">
                    @error('price')
                    <div class="error">{{ $message }}</div>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="desc">Descripcion</label>
                    <input id="desc" type="text" name="desc" value="" class="form-control">
                </div>
                <div class="form-group">
                    <label for="desc">Categoria</label>
                    <select class="form-control" id="category" name="category">
                        @foreach ($categories as $cat)
                        <option value="{{$cat->id}}">{{$cat->name}}</option>
                        @endforeach
                    </select>
                </div>
                <div class="form-group">
                    <label for="imagen">Imagen</label>
                    <input type="file" name="imagen" />
                </div>
                <div class="form-group">
                    <input type="submit" value="Guardar" class="btn btn-primary">
                </div>
            </form>
        </div>
    </div>
    @if(app('request')->has('success'))
    @if (session('error'))
    <div class="alert alert-danger">
        {{ session('error') }}
    </div>
    @else
    <div class="alert alert-success">
        Producto guardado con exito
    </div>
    @endif
    @endif
</x-guest-layout>

resources/views/products.blade.php
<x-guest-layout>
    <h1>Lista de Productos</h1>
    <div class="row">
        @forelse ($productos as $prod)
        <div class="col-lg-4 text-center mb-4">
            <img width="140" class="rounded-circle" src="{{ ($prod->imagen)?$prod->imagen:asset('img/Imagen-no-disponible.png') }}">
            <h2>{{ $prod->name }}</h2>
            <p>{{ $prod->desc }}</p>
            <h3>{{ $prod->price }} €</h3>
            <p>{{ $prod->category }}</p>
            <form method="post" action={{ route('addToChart') }}>
                {{ csrf_field() }}
                <input type="hidden" name="productid" value="{{$prod->id}}">
                <input type="hidden" name="productname" value="{{$prod->name}}">
                <input type="submit" value="Add product to shipping »" class="btn btn-secondary">
            </form>
        </div>
        @empty
        <p>No products</p>
        @endforelse
    </div>
    <!--Excluimos el menu en caso de que sea peticion AJAX-->
    @if(!Request::ajax())
    <div class="container">
        <div class="card gx-5">
            <div class="card-body">
                <h3>Filtrar Productos</h3>
                <form id="filterForm" method="post" action="/products">
                    {{ csrf_field() }}
                    <div class="form-group">
                        <label for="priceMin">Precio Min</label>
                        <input id="priceMin" type="text" name="priceMin" value="{{ old('priceMin') }}" class="form-control">
                    </div>

                    <div class="form-group">
                        <label for="priceMax">Precio Max</label>
                        <input id="priceMax" type="text" name="priceMax" value="{{ old('priceMax') }}" class="form-control">
                    </div>
                    <div class="form-group">
                        <label for="name">Name</label>
                        <input id="name" type="text" name="name" value="{{ old('name') }}" class="form-control">
                    </div>
                    <div class="form-group">
                        <label for="name">Type</label>
                        <input id="type" type="text" name="type" value="{{ old('type') }}" class="form-control">
                    </div>
                    <div class="form-check">
                        <input type="checkbox" class="form-check-input" id="axios" name="axios" {{ (old('axios'))?'checked':'' }}>
                        <label class="form-check-label" for="axios">Filter by Axios</label>
                    </div>
                    <input type="submit" value="Filter" class="btn btn-primary">
                </form>
            </div>
        </div>
    </div>

    <script>
        $('#filterForm').submit(function(e) {
            //Si la opcion de Axios (async) esta activada, realizaremos un submit asincrono con este script
            if ($('#axios').is(':checked')) {
                e.preventDefault()
                //Datos del formulario lo guardamos como json en data
                var data = $("#filterForm").serialize()
                axios.post('products', data)
                    .then(response => {
                        console.log(response)
                        //La respuesta obtenida de la petición Ajax la pegamos en nuestra web
                        //substituyendo el content actual (no el menu de filtros)
                        $('#content').replaceWith(response.data)
                    })
            }
        })
    </script>
    @endif
</x-guest-layout>